on:
  push:
    tags:
    - 'v*'

name: Create Release Draft

jobs:
  build:
    name: Create Release Asset
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@master
      - name: Check version tag
        run: |
          [[ \
            `git tag --points-at` \
            == \
            v`jq -r '.["semantic-version"] + "-gnome" + .["shell-version"][-1]' sources/metadata.json` \
          ]]
      - name: Build project
        run: |
          shopt -s expand_aliases
          alias eslint="npx eslint"
          sudo apt-get install gettext
          npm install eslint
          make lint zip
      - name: Draft Release
        id: draft_release
        uses: actions/create-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ github.ref }}
          release_name: ${{ github.ref }}
          draft: true
          prerelease: false
      - name: Upload Package
        id: upload-package
        uses: actions/upload-release-asset@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.draft_release.outputs.upload_url }}
          asset_path: ./build/io.github.mreditor.gnome-shell-extensions.scroll-panel.zip
          asset_name: io.github.mreditor.gnome-shell-extensions.scroll-panel.zip
          asset_content_type: application/zip
